### ISSUE TITLE
Ps not initalized error for pro users 

### ISSUE THREAD

**Issue by abhijitgujar86** [SpellCraft/mdb4-boilerplate#1]
Error :  25:3  error  'Ps' is not defined  no-undef

Ps.initialize(sideNavScrollbar);

https://mdbootstrap.com/javascript/sidenav/

How to fix this ? I already did step 3 while setting up webpack as instructed . I am Pro user.

**Comment by SpellCraft** [comment]
I'm working on re-writing the entire project to better explain a few things and also clean up a few bugs I've encountered.
```JavaScript
Ps.initialize(...);
```
Isn't needed to make the Side Navigation component to work as it should! Simply binding ***.sideNav();*** to an element is all that's needed.

```JavaScript
// Initialize the side navigation
$('.button-collapse').sideNav('toggle');
```

If you still want to have Ps.initialize() in your code, you can simply make ESlint skip the line by adding this:
```JavaScript
// eslint-disable-next-line
Ps.initialize(sideNavScrollbar);
```

Hope that helps!

**Comment by abhijitgujar86** [comment]
yes , that works still i did not got the use or functionality of it .
