### ISSUE TITLE
How to include add ons?

### ISSUE THREAD

**Issue by paradoxpotato** [SpellCraft/mdb4-boilerplate#5]
Hey there, I bought mdb pro and some addons, the webpacking of the pro package works like a charm, but  it is not obvious how to compile add ons (calendar and draggable) aswell. Can you give me a hint?

**Comment by SpellCraft** [comment]
Hello mate, sorry for the late reply.

To enable the addons, simply include the JS files required in /src/js/app.js and SCSS files within /src/scss/main.scss

Datatables was the only addon available when I last updated the repository, you can use that as a guide to include the other addons. :) Let me know if you run into any issues.
