### ISSUE TITLE
Quick doc fix

### ISSUE THREAD

**Issue by richb-hanover** [SpellCraft/mdb4-boilerplate#8]
README.md should include a `cd  mdb4-boilerplate` statement, like this:

```
# Clone the project
# Note that the --recursive is required to retrieve external repositories
git clone --recursive https://github.com/SpellCraft/mdb4-boilerplate.git

# change to the mdb4-boilerplate directory
cd mdb4-boilerplate

# Then install dependencies
npm install
```
Also include the note about --recursive so dopes (like me) will use it the first time. Thanks.

**Comment by SpellCraft** [comment]
Thanks for the input!

The new version of the repository aimed at 4.7.7 and up will automatically install MDB together with the project through NPM.
